### ISSUE TITLE
[Feature Request] Make website a bit more interactive

### ISSUE THREAD

**Issue by museHD** [rammcodes/Dopefolio#13]
The project looks great, however the website could be made a lot more interactive by adding hover animations and a few moving elements. 

Easy things such as:
- Box Shadow for buttons upon hover
- Animated fill for social media icons upon hover
- Animated headings/text when website is first opened
- etc.

Most of these should be easy to add and I'd be happy to contribute.

**Comment by Vikram-Hegde** [comment]
I too would be happy to contribute any of the above mentioned things.

**Comment by museHD** [comment]
Looks like @rammcodes implemented this in a6effae.
Looks nice!
