### ISSUE TITLE
Query required Using This Template

### ISSUE THREAD

**Issue by Tanmoy741127** [rammcodes/Dopefolio#22]
I am currently building an open source platform where developers can create and manage their portfolio and switch between templates easily.
I like the simplicity of this design.

Can I integrate this in the platform ?
Proper source code link of this github repo and author's name will be mentoned under template .

**Comment by Tanmoy741127** [comment]
@rammcodes can you please answer my query ?

**Comment by rammcodes** [comment]
@Tanmoy741127 Yeah, you can use this template in your platform as long as you will provide credits to the Author of the template :)

**Comment by Tanmoy741127** [comment]
Thank you @rammcodes for the confirmation .
