### ISSUE TITLE
library is not supported 

### ISSUE THREAD

**Issue by umerimranqureshi** [rammcodes/Dopefolio#27]
i have getting errors while installing npm

<img width="1440" alt="Screen Shot 2023-01-24 at 4 14 54 PM" src="https://user-images.githubusercontent.com/37175672/214417919-242afbb4-4c5a-49d5-8971-2b8ffd1ecd6d.png">

**Comment by kenchung285** [comment]
@umerimranqureshi
Hi, I got the same error in node@18.20.5. Have you addressed this issue?

**Comment by kenchung285** [comment]
I have solved the issue and explained in details [here](https://github.com/rammcodes/Dopefolio/issues/29#issuecomment-2501219823)
