### ISSUE TITLE
Add PWA support 

### ISSUE THREAD

**Issue by Aniket762** [rammcodes/Dopefolio#4]
Hey @rammcodes , awesome work with Dopefolio, I would like to add PWA support to dopefolio, let me know if I can start working on it. PWA's are designed to combine the best features of mobile apps and the mobile web such as speed and offline usage, without downloading anything.

**Comment by rammcodes** [comment]
Hey @Aniket762 , PWA support will be a great addition to Dopefolio, You can start working on it on a new branch and create a PR once you are done with it. Take your time and no need to rush, You can work on it whenever you are free in the coming days. I'm glad that you are interested to contribute. Thank You 😄

**Comment by Aniket762** [comment]
On it @rammcodes

**Comment by rammcodes** [comment]
@Aniket762 Your PR looks really great. You have done a great job. Yesterday, I had a conversation with 1-2 Udemy instructors and they plan to add Dopefolio in their course curriculum teaching their students how to create a portfolio website using this Repo. So, it will be great for the entire project as those courses are the top-rated courses on udemy so in that way we will have a constant flow of people using the repo for many months or even years.

The only problem that they told me is to keep the Repo as simple as possible, I asked them if it's fine to have PWA support then they told me to avoid having PWA support as many of the students are beginners and PWA is one advanced feature so it will confuse them to set up their own website so they suggested me to just keep it without PWA.

As you have done a great job and everything that you have implemented looks awesome. For now, I will have to avoid merging the PR into the main branch as you know the reason stated above. I'm really sorry for that. As I said, your solution is perfect but just to keep the repo as simple as possible for beginners, I will have to avoid merging it for now. I'm really sorry once again. I will still like to give you a shoutout and I will see how I can add your name to the contributors list. I'm really very thankful for your contribution.

**Comment by Aniket762** [comment]
Hey @rammcodes that's awesome man, congratulations! Let's connect over [LinkedIn](https://linkedin.com/in/aniket-pal) , wanna learn about stargazing from you! Again keep up the good work! 🚀
